# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l9Qr1FX6AWfAiuYrhuVOXTTzpV94NLHe
"""

pip install pysam

"""Function"""

import pysam as ps

file_path = './merged-tumor.bam'

count_reads = 0
count_unmapped = 0
count_quality_zero = 0
sum_quality = 0
sum_filtered = 0
  
fasta = ps.AlignmentFile(file_path)

counter = 0

for read in fasta:
  # No need to print them all, so after 10th...
  if counter == 0:
    print(read)
    print("")
    print(read.flag)
    counter += 10
    
  if counter == 10:
    print(read.flag)
    counter += 1

  # Main work
  if read.flag & 4:
      count_unmapped += 1

  count_reads += 1
  quality = read.mapping_quality

  if read.mapping_quality == 0:
      count_quality_zero += 1
  else:
      sum_filtered += quality

  sum_quality += quality


# Additional calculations
avg_quality = sum_quality / count_reads
avg_filtered_quality = sum_filtered /(count_reads - count_quality_zero)

print("")
print("")
print("CALCULATIONS:")
print("Num. of unmapped reads: ", count_unmapped)
print("Num. of reads: ", count_reads)
print("Num. of reads with mapping quality of 0: ", count_quality_zero)
print("Avg. mapping quality: ", avg_quality)
print("Avg. mapping quality when reads with quality of 0 are filtered out: ", avg_filtered_quality)